import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const locations = [
  // ZONE 1: SOUTH CAMPUS (TP Ganesan Auditorium, Kattankulathur Station & Plaza)
  {
    id: 'loc_tp_ganesan_auditorium',
    name: 'Dr. T.P. Ganesan Auditorium',
    latitude: 12.821340,
    longitude: 80.038410,
    panoId: 'tp_auditorium_wide',
    imageUrl: '/images/locations/loc_tp_ganesan_auditorium.jpg',
    area: 'South Campus',
    difficulty: 'easy',
    active: true,
  },
  {
    id: 'loc_auditorium_entrance',
    name: 'TP Ganesan Auditorium Entrance Portico',
    latitude: 12.821420,
    longitude: 80.038550,
    panoId: 'auditorium_entrance',
    imageUrl: '/images/locations/loc_auditorium_entrance.jpg',
    area: 'South Campus',
    difficulty: 'medium',
    active: true,
  },
  {
    id: 'loc_auditorium_plaza',
    name: 'Auditorium Steps & Fountain Plaza',
    latitude: 12.821550,
    longitude: 80.038680,
    panoId: 'auditorium_plaza',
    imageUrl: '/images/locations/loc_auditorium_plaza.jpg',
    area: 'South Campus',
    difficulty: 'medium',
    active: true,
  },
  {
    id: 'loc_auditorium_dome_zoom',
    name: 'Auditorium Curved Dome Facade (Zoomed Detail)',
    latitude: 12.821340,
    longitude: 80.038410,
    panoId: 'auditorium_dome_zoom',
    imageUrl: '/images/locations/loc_auditorium_dome_zoom.jpg',
    area: 'South Campus',
    difficulty: 'hard',
    active: true,
  },
  {
    id: 'loc_auditorium_arch',
    name: 'Auditorium Cantilevered Roof Arch',
    latitude: 12.821280,
    longitude: 80.038350,
    panoId: 'auditorium_arch',
    imageUrl: '/images/locations/loc_auditorium_arch.jpg',
    area: 'South Campus',
    difficulty: 'hard',
    active: true,
  },
  {
    id: 'loc_kattankulathur_station',
    name: 'Kattankulathur Railway Station Platform',
    latitude: 12.819820,
    longitude: 80.036950,
    panoId: 'kattankulathur_station',
    imageUrl: '/images/locations/loc_kattankulathur_station.jpg',
    area: 'South Campus',
    difficulty: 'medium',
    active: true,
  },
  {
    id: 'loc_kattankulathur_station_tracks',
    name: 'Kattankulathur Suburban Rail Line',
    latitude: 12.819950,
    longitude: 80.037120,
    panoId: 'kattankulathur_station_tracks',
    imageUrl: '/images/locations/loc_kattankulathur_station_tracks.jpg',
    area: 'South Campus',
    difficulty: 'medium',
    active: true,
  },
  {
    id: 'loc_kattankulathur_tracks_zoom',
    name: 'Kattankulathur Rail Curves & Overhead Catenary',
    latitude: 12.819680,
    longitude: 80.036810,
    panoId: 'kattankulathur_tracks_zoom',
    imageUrl: '/images/locations/loc_kattankulathur_tracks_zoom.jpg',
    area: 'South Campus',
    difficulty: 'hard',
    active: true,
  },

  // ZONE 2: NORTH CAMPUS / TECH PARK (IT Block, Spire & Canteen Walkway)
  {
    id: 'loc_tech_park',
    name: 'Tech Park (TP) IT Tower',
    latitude: 12.824705,
    longitude: 80.045230,
    panoId: 'tech_park_wide',
    imageUrl: '/images/locations/loc_tech_park.jpg',
    area: 'North Campus',
    difficulty: 'easy',
    active: true,
  },
  {
    id: 'loc_tech_park_zoom',
    name: 'Tech Park Entrance Pillars (Zoomed Detail)',
    latitude: 12.824705,
    longitude: 80.045230,
    panoId: 'tech_park_zoom',
    imageUrl: '/images/locations/loc_tech_park_zoom.jpg',
    area: 'North Campus',
    difficulty: 'hard',
    active: true,
  },
  {
    id: 'loc_tech_park_facade',
    name: 'Tech Park Upper Glass Curtain Facade',
    latitude: 12.824850,
    longitude: 80.045350,
    panoId: 'tech_park_facade',
    imageUrl: '/images/locations/loc_tech_park_facade.jpg',
    area: 'North Campus',
    difficulty: 'hard',
    active: true,
  },
  {
    id: 'loc_tech_park_spire',
    name: 'Tech Park Spire & Sky Atrium',
    latitude: 12.824920,
    longitude: 80.045410,
    panoId: 'tech_park_spire',
    imageUrl: '/images/locations/loc_tech_park_spire.jpg',
    area: 'North Campus',
    difficulty: 'hard',
    active: true,
  },
  {
    id: 'loc_tech_park_canteen_walk',
    name: 'Tech Park Lower Plaza & Canteen Way',
    latitude: 12.824580,
    longitude: 80.045100,
    panoId: 'tech_park_canteen_walk',
    imageUrl: '/images/locations/loc_tech_park_canteen_walk.jpg',
    area: 'North Campus',
    difficulty: 'medium',
    active: true,
  },

  // ZONE 3: POTHERI / WEST CAMPUS (Overpass, Station Platforms & GST Highway)
  {
    id: 'loc_potheri_railway_bridge',
    name: 'Potheri Railway Overpass & GST Junction',
    latitude: 12.825634,
    longitude: 80.039845,
    panoId: 'potheri_bridge_wide',
    imageUrl: '/images/locations/loc_potheri_railway_bridge.jpg',
    area: 'Potheri / West',
    difficulty: 'easy',
    active: true,
  },
  {
    id: 'loc_potheri_zoom',
    name: 'Potheri Station Overpass (Zoomed Detail)',
    latitude: 12.825634,
    longitude: 80.039845,
    panoId: 'potheri_zoom',
    imageUrl: '/images/locations/loc_potheri_zoom.jpg',
    area: 'Potheri / West',
    difficulty: 'hard',
    active: true,
  },
  {
    id: 'loc_potheri_platform_view',
    name: 'Potheri Railway Platform & Tracks',
    latitude: 12.825820,
    longitude: 80.040120,
    panoId: 'potheri_platform_view',
    imageUrl: '/images/locations/loc_potheri_platform_view.jpg',
    area: 'Potheri / West',
    difficulty: 'medium',
    active: true,
  },
  {
    id: 'loc_potheri_station_entrance',
    name: 'Potheri Station West Entrance Arch',
    latitude: 12.825910,
    longitude: 80.039620,
    panoId: 'potheri_station_entrance',
    imageUrl: '/images/locations/loc_potheri_station_entrance.jpg',
    area: 'Potheri / West',
    difficulty: 'medium',
    active: true,
  },
  {
    id: 'loc_potheri_bridge_stairs',
    name: 'Potheri Footbridge Staircase Clue',
    latitude: 12.825550,
    longitude: 80.039780,
    panoId: 'potheri_bridge_stairs',
    imageUrl: '/images/locations/loc_potheri_bridge_stairs.jpg',
    area: 'Potheri / West',
    difficulty: 'hard',
    active: true,
  },
  {
    id: 'loc_potheri_tracks_overhead',
    name: 'Potheri High-Voltage Cantilever & Rails',
    latitude: 12.826010,
    longitude: 80.040250,
    panoId: 'potheri_tracks_overhead',
    imageUrl: '/images/locations/loc_potheri_tracks_overhead.jpg',
    area: 'Potheri / West',
    difficulty: 'hard',
    active: true,
  },
  {
    id: 'loc_potheri_gate_approach',
    name: 'Potheri Station Approach Roadway',
    latitude: 12.825780,
    longitude: 80.039520,
    panoId: 'potheri_gate_approach',
    imageUrl: '/images/locations/loc_potheri_gate_approach.jpg',
    area: 'Potheri / West',
    difficulty: 'medium',
    active: true,
  },

  // ZONE 4: CENTRAL CAMPUS (Java Green, Clock Tower & Central Avenue)
  {
    id: 'loc_java_green_clock_tower',
    name: 'Java Green & Clock Tower',
    latitude: 12.823120,
    longitude: 80.043810,
    panoId: 'clock_tower_java',
    imageUrl: '/images/locations/loc_java_green_clock_tower.jpg',
    area: 'Central Campus',
    difficulty: 'easy',
    active: true,
  },
  {
    id: 'loc_java_green_lawns',
    name: 'Java Green Seating Lawns Corner',
    latitude: 12.823250,
    longitude: 80.043920,
    panoId: 'java_green_lawns',
    imageUrl: '/images/locations/loc_java_green_lawns.jpg',
    area: 'Central Campus',
    difficulty: 'medium',
    active: true,
  },
  {
    id: 'loc_campus_walkway',
    name: 'SRM Central Avenue Walkway',
    latitude: 12.824120,
    longitude: 80.044120,
    panoId: 'campus_walkway_avenue',
    imageUrl: '/images/locations/loc_campus_walkway.jpg',
    area: 'Central Campus',
    difficulty: 'medium',
    active: true,
  },
  {
    id: 'loc_campus_walkway_close',
    name: 'Central Walkway Tree Canopy (Zoomed Detail)',
    latitude: 12.824120,
    longitude: 80.044120,
    panoId: 'campus_walkway_close',
    imageUrl: '/images/locations/loc_campus_walkway_close.jpg',
    area: 'Central Campus',
    difficulty: 'hard',
    active: true,
  },
  {
    id: 'loc_central_boulevard',
    name: 'SRM Main Campus Boulevard Corridor',
    latitude: 12.823950,
    longitude: 80.044350,
    panoId: 'central_boulevard',
    imageUrl: '/images/locations/loc_central_boulevard.jpg',
    area: 'Central Campus',
    difficulty: 'hard',
    active: true,
  },

  // ZONE 5: EAST CAMPUS / ACADEMIC BLOCKS (Bioengineering, Old Campus & Academic Block)
  {
    id: 'loc_academic_block_new',
    name: 'SRM Academic Block (2026 View)',
    latitude: 12.823612,
    longitude: 80.044521,
    panoId: 'academic_block_2026',
    imageUrl: '/images/locations/loc_academic_block_new.jpg',
    area: 'East Academic',
    difficulty: 'medium',
    active: true,
  },
  {
    id: 'loc_academic_windows_zoom',
    name: 'Academic Block Glass & Louver Matrix',
    latitude: 12.823720,
    longitude: 80.044610,
    panoId: 'academic_windows_zoom',
    imageUrl: '/images/locations/loc_academic_windows_zoom.jpg',
    area: 'East Academic',
    difficulty: 'hard',
    active: true,
  },
  {
    id: 'loc_old_campus',
    name: 'Old Engineering Campus Wing (August 2024)',
    latitude: 12.823850,
    longitude: 80.042810,
    panoId: 'old_campus_aug2024',
    imageUrl: '/images/locations/loc_old_campus.jpg',
    area: 'East Academic',
    difficulty: 'medium',
    active: true,
  },
  {
    id: 'loc_old_campus_arcade',
    name: 'Old Engineering Red Brick Arcade Corridor',
    latitude: 12.823920,
    longitude: 80.042950,
    panoId: 'old_campus_arcade',
    imageUrl: '/images/locations/loc_old_campus_arcade.jpg',
    area: 'East Academic',
    difficulty: 'hard',
    active: true,
  },
  {
    id: 'loc_bio_engineering_block',
    name: 'School of Bioengineering Entrance',
    latitude: 12.822530,
    longitude: 80.045120,
    panoId: 'bio_engineering_block',
    imageUrl: '/images/locations/loc_bio_engineering_block.jpg',
    area: 'East Academic',
    difficulty: 'medium',
    active: true,
  },
  {
    id: 'loc_bio_lab_entrance',
    name: 'Bioengineering Research Lab Portal',
    latitude: 12.822640,
    longitude: 80.045250,
    panoId: 'bio_lab_entrance',
    imageUrl: '/images/locations/loc_bio_lab_entrance.jpg',
    area: 'East Academic',
    difficulty: 'hard',
    active: true,
  },

  // ZONE 6: CAMPUS LANDMARKS & MAIN BOULEVARDS (UB, Main Gate Arch & Lake)
  {
    id: 'loc_ub_front',
    name: 'SRM University Building & Central Library',
    latitude: 12.823450,
    longitude: 80.045650,
    panoId: 'ub_front_facade',
    imageUrl: '/images/locations/loc_ub_front.jpg',
    area: 'Central Campus',
    difficulty: 'easy',
    active: true,
  },
  {
    id: 'loc_ub_lake_view',
    name: 'University Building Reflecting on Potheri Lake',
    latitude: 12.827200,
    longitude: 80.043500,
    panoId: 'ub_lake_view',
    imageUrl: '/images/locations/loc_ub_lake_view.jpg',
    area: 'Lake View',
    difficulty: 'medium',
    active: true,
  },
  {
    id: 'loc_tech_park_lawn_statue',
    name: 'Tech Park Lawn & Tree of Wisdom Sculpture',
    latitude: 12.824250,
    longitude: 80.045050,
    panoId: 'tech_park_lawn_statue',
    imageUrl: '/images/locations/loc_tech_park_lawn_statue.jpg',
    area: 'North Campus',
    difficulty: 'medium',
    active: true,
  },
  {
    id: 'loc_srm_main_arch_gate',
    name: 'SRM Main Entrance Grand Arch Gate (GST Road)',
    latitude: 12.823050,
    longitude: 80.041350,
    panoId: 'srm_main_arch_gate',
    imageUrl: '/images/locations/loc_srm_main_arch_gate.jpg',
    area: 'Main Entrance',
    difficulty: 'easy',
    active: true,
  },
  {
    id: 'loc_srm_palm_boulevard',
    name: 'SRM Royal Palm Avenue Driveway',
    latitude: 12.823500,
    longitude: 80.042200,
    panoId: 'srm_palm_boulevard',
    imageUrl: '/images/locations/loc_srm_palm_boulevard.jpg',
    area: 'Central Campus',
    difficulty: 'medium',
    active: true,
  },

  // ZONE 7: OFFICIAL SRMIST 360° VIRTUAL TOUR SITES
  {
    id: 'loc_tour_clock_tower_360',
    name: 'SRM Clock Tower & Java Green Plaza (360°)',
    latitude: 12.823120,
    longitude: 80.043810,
    panoId: 'tour_clock_tower_360',
    imageUrl: '/images/locations/loc_tour_clock_tower_360.jpg',
    area: 'Central Campus',
    difficulty: 'easy',
    active: true,
  },
  {
    id: 'loc_tour_chola_statue_360',
    name: "Chola's Statue & Central Island Roundabout (360°)",
    latitude: 12.823350,
    longitude: 80.044950,
    panoId: 'tour_chola_statue_360',
    imageUrl: '/images/locations/loc_tour_chola_statue_360.jpg',
    area: 'Central Campus',
    difficulty: 'easy',
    active: true,
  },
  {
    id: 'loc_tour_football_ground_360',
    name: 'SRM Football Ground & Mega Hostels (360°)',
    latitude: 12.820200,
    longitude: 80.042500,
    panoId: 'tour_football_ground_360',
    imageUrl: '/images/locations/loc_tour_football_ground_360.jpg',
    area: 'Sports Arena',
    difficulty: 'medium',
    active: true,
  },
  {
    id: 'loc_tour_sports_arena_360',
    name: 'SRM Outdoor Sports Arena & Athletic Complex (360°)',
    latitude: 12.819800,
    longitude: 80.043200,
    panoId: 'tour_sports_arena_360',
    imageUrl: '/images/locations/loc_tour_sports_arena_360.jpg',
    area: 'Sports Arena',
    difficulty: 'medium',
    active: true,
  },
  {
    id: 'loc_tour_paari_hostel',
    name: "Paari & Oori Men's Hostel Main Gate & Arch",
    latitude: 12.821800,
    longitude: 80.046100,
    panoId: 'tour_paari_hostel',
    imageUrl: '/images/locations/loc_tour_paari_hostel.jpg',
    area: 'Hostel Zone',
    difficulty: 'easy',
    active: true,
  },
  {
    id: 'loc_tour_oori_hostel_360',
    name: 'Oori Hostel Block Avenue (360°)',
    latitude: 12.821500,
    longitude: 80.046400,
    panoId: 'tour_oori_hostel_360',
    imageUrl: '/images/locations/loc_tour_oori_hostel_360.jpg',
    area: 'Hostel Zone',
    difficulty: 'medium',
    active: true,
  },
  {
    id: 'loc_tour_nelson_mandela',
    name: 'Nelson Mandela Hostel Block Courtyard',
    latitude: 12.820500,
    longitude: 80.047100,
    panoId: 'tour_nelson_mandela',
    imageUrl: '/images/locations/loc_tour_nelson_mandela.jpg',
    area: 'Hostel Zone',
    difficulty: 'medium',
    active: true,
  },
  {
    id: 'loc_tour_architecture',
    name: 'School of Architecture & Interior Design',
    latitude: 12.823900,
    longitude: 80.046200,
    panoId: 'tour_architecture',
    imageUrl: '/images/locations/loc_tour_architecture.jpg',
    area: 'East Academic',
    difficulty: 'medium',
    active: true,
  },
  {
    id: 'loc_tour_school_of_law',
    name: 'School of Law Main Entrance Facade',
    latitude: 12.824300,
    longitude: 80.046700,
    panoId: 'tour_school_of_law',
    imageUrl: '/images/locations/loc_tour_school_of_law.jpg',
    area: 'East Academic',
    difficulty: 'medium',
    active: true,
  },
  {
    id: 'loc_tour_school_of_management',
    name: 'School of Management Portal',
    latitude: 12.823200,
    longitude: 80.046500,
    panoId: 'tour_school_of_management',
    imageUrl: '/images/locations/loc_tour_school_of_management.jpg',
    area: 'East Academic',
    difficulty: 'medium',
    active: true,
  },
  {
    id: 'loc_tour_campus_temple_360',
    name: 'SRM Campus Ganesha Temple (MG Road) (360°)',
    latitude: 12.822700,
    longitude: 80.043500,
    panoId: 'tour_campus_temple_360',
    imageUrl: '/images/locations/loc_tour_campus_temple_360.jpg',
    area: 'Central Campus',
    difficulty: 'medium',
    active: true,
  },
  {
    id: 'loc_tour_srm_hospital',
    name: 'SRM General Hospital & Research Centre',
    latitude: 12.824800,
    longitude: 80.048500,
    panoId: 'tour_srm_hospital',
    imageUrl: '/images/locations/loc_tour_srm_hospital.jpg',
    area: 'Medical / Hospital',
    difficulty: 'easy',
    active: true,
  },
  {
    id: 'loc_tour_dental_college_360',
    name: 'SRM Kattankulathur Dental College (360°)',
    latitude: 12.825200,
    longitude: 80.047800,
    panoId: 'tour_dental_college_360',
    imageUrl: '/images/locations/loc_tour_dental_college_360.jpg',
    area: 'Medical / Hospital',
    difficulty: 'medium',
    active: true,
  },
  {
    id: 'loc_tour_cv_raman_park',
    name: 'Sir C.V. Raman Research Park',
    latitude: 12.824100,
    longitude: 80.045800,
    panoId: 'tour_cv_raman_park',
    imageUrl: '/images/locations/loc_tour_cv_raman_park.jpg',
    area: 'North Campus',
    difficulty: 'hard',
    active: true,
  },
  {
    id: 'loc_tour_aerospace_hangar',
    name: 'Aerospace Engineering Flight Hangar',
    latitude: 12.822200,
    longitude: 80.044300,
    panoId: 'tour_aerospace_hangar',
    imageUrl: '/images/locations/loc_tour_aerospace_hangar.jpg',
    area: 'Central Campus',
    difficulty: 'hard',
    active: true,
  },
  {
    id: 'loc_tour_supermarket',
    name: 'Campus Super Market & Food Court Square',
    latitude: 12.822100,
    longitude: 80.045500,
    panoId: 'tour_supermarket',
    imageUrl: '/images/locations/loc_tour_supermarket.jpg',
    area: 'Hostel Zone',
    difficulty: 'medium',
    active: true,
  },
  {
    id: 'loc_tour_hostel_sunset',
    name: 'SRM Hostel Sunset Courtyard Avenue',
    latitude: 12.821400,
    longitude: 80.046800,
    panoId: 'tour_hostel_sunset',
    imageUrl: '/images/locations/loc_tour_hostel_sunset.jpg',
    area: 'Hostel Zone',
    difficulty: 'hard',
    active: true,
  },
];

async function main() {
  console.log('Seeding progressive difficulty locations with real photos...');
  // Clear non-current locations so only verified real photos are active
  await prisma.location.updateMany({ data: { active: false } });

  for (const loc of locations) {
    await prisma.location.upsert({
      where: { id: loc.id },
      update: loc,
      create: loc,
    });
  }
  const count = await prisma.location.count({ where: { active: true } });
  console.log(`Successfully seeded ${count} active locations across Easy, Medium, and Hard difficulty!`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
