import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const locations = [
  // ZONE 1: SOUTH CAMPUS (TP Ganesan Auditorium, Kattankulathur Station & Plaza)
  {
    id: 'loc_tp_ganesan_auditorium',
    name: 'Dr. T.P. Ganesan Auditorium',
    latitude: 12.821340,
    longitude: 80.038410,
    panoId: 'tp_auditorium_wide',
    imageUrl: '/images/locations/loc_tp_ganesan_auditorium.jpg',
    area: 'South Campus',
    difficulty: 'easy',
    active: true,
  },
  {
    id: 'loc_auditorium_entrance',
    name: 'TP Ganesan Auditorium Entrance Portico',
    latitude: 12.821420,
    longitude: 80.038550,
    panoId: 'auditorium_entrance',
    imageUrl: '/images/locations/loc_auditorium_entrance.jpg',
    area: 'South Campus',
    difficulty: 'medium',
    active: true,
  },
  {
    id: 'loc_auditorium_plaza',
    name: 'Auditorium Steps & Fountain Plaza',
    latitude: 12.821550,
    longitude: 80.038680,
    panoId: 'auditorium_plaza',
    imageUrl: '/images/locations/loc_auditorium_plaza.jpg',
    area: 'South Campus',
    difficulty: 'medium',
    active: true,
  },
  {
    id: 'loc_auditorium_dome_zoom',
    name: 'Auditorium Curved Dome Facade (Zoomed Detail)',
    latitude: 12.821340,
    longitude: 80.038410,
    panoId: 'auditorium_dome_zoom',
    imageUrl: '/images/locations/loc_auditorium_dome_zoom.jpg',
    area: 'South Campus',
    difficulty: 'hard',
    active: true,
  },
  {
    id: 'loc_auditorium_arch',
    name: 'Auditorium Cantilevered Roof Arch',
    latitude: 12.821280,
    longitude: 80.038350,
    panoId: 'auditorium_arch',
    imageUrl: '/images/locations/loc_auditorium_arch.jpg',
    area: 'South Campus',
    difficulty: 'hard',
    active: true,
  },
  {
    id: 'loc_kattankulathur_station',
    name: 'Kattankulathur Railway Station Platform',
    latitude: 12.819820,
    longitude: 80.036950,
    panoId: 'kattankulathur_station',
    imageUrl: '/images/locations/loc_kattankulathur_station.jpg',
    area: 'South Campus',
    difficulty: 'medium',
    active: true,
  },
  {
    id: 'loc_kattankulathur_station_tracks',
    name: 'Kattankulathur Suburban Rail Line',
    latitude: 12.819950,
    longitude: 80.037120,
    panoId: 'kattankulathur_station_tracks',
    imageUrl: '/images/locations/loc_kattankulathur_station_tracks.jpg',
    area: 'South Campus',
    difficulty: 'medium',
    active: true,
  },
  {
    id: 'loc_kattankulathur_tracks_zoom',
    name: 'Kattankulathur Rail Curves & Overhead Catenary',
    latitude: 12.819680,
    longitude: 80.036810,
    panoId: 'kattankulathur_tracks_zoom',
    imageUrl: '/images/locations/loc_kattankulathur_tracks_zoom.jpg',
    area: 'South Campus',
    difficulty: 'hard',
    active: true,
  },

  // ZONE 2: NORTH CAMPUS / TECH PARK (IT Block, Spire & Canteen Walkway)
  {
    id: 'loc_tech_park',
    name: 'Tech Park (TP) IT Tower',
    latitude: 12.824705,
    longitude: 80.045230,
    panoId: 'tech_park_wide',
    imageUrl: '/images/locations/loc_tech_park.jpg',
    area: 'North Campus',
    difficulty: 'easy',
    active: true,
  },
  {
    id: 'loc_tech_park_zoom',
    name: 'Tech Park Entrance Pillars (Zoomed Detail)',
    latitude: 12.824705,
    longitude: 80.045230,
    panoId: 'tech_park_zoom',
    imageUrl: '/images/locations/loc_tech_park_zoom.jpg',
    area: 'North Campus',
    difficulty: 'hard',
    active: true,
  },
  {
    id: 'loc_tech_park_facade',
    name: 'Tech Park Upper Glass Curtain Facade',
    latitude: 12.824850,
    longitude: 80.045350,
    panoId: 'tech_park_facade',
    imageUrl: '/images/locations/loc_tech_park_facade.jpg',
    area: 'North Campus',
    difficulty: 'hard',
    active: true,
  },
  {
    id: 'loc_tech_park_spire',
    name: 'Tech Park Spire & Sky Atrium',
    latitude: 12.824920,
    longitude: 80.045410,
    panoId: 'tech_park_spire',
    imageUrl: '/images/locations/loc_tech_park_spire.jpg',
    area: 'North Campus',
    difficulty: 'hard',
    active: true,
  },
  {
    id: 'loc_tech_park_canteen_walk',
    name: 'Tech Park Lower Plaza & Canteen Way',
    latitude: 12.824580,
    longitude: 80.045100,
    panoId: 'tech_park_canteen_walk',
    imageUrl: '/images/locations/loc_tech_park_canteen_walk.jpg',
    area: 'North Campus',
    difficulty: 'medium',
    active: true,
  },

  // ZONE 3: POTHERI / WEST CAMPUS (Overpass, Station Platforms & GST Highway)
  {
    id: 'loc_potheri_railway_bridge',
    name: 'Potheri Railway Overpass & GST Junction',
    latitude: 12.825634,
    longitude: 80.039845,
    panoId: 'potheri_bridge_wide',
    imageUrl: '/images/locations/loc_potheri_railway_bridge.jpg',
    area: 'Potheri / West',
    difficulty: 'easy',
    active: true,
  },
  {
    id: 'loc_potheri_zoom',
    name: 'Potheri Station Overpass (Zoomed Detail)',
    latitude: 12.825634,
    longitude: 80.039845,
    panoId: 'potheri_zoom',
    imageUrl: '/images/locations/loc_potheri_zoom.jpg',
    area: 'Potheri / West',
    difficulty: 'hard',
    active: true,
  },
  {
    id: 'loc_potheri_platform_view',
    name: 'Potheri Railway Platform & Tracks',
    latitude: 12.825820,
    longitude: 80.040120,
    panoId: 'potheri_platform_view',
    imageUrl: '/images/locations/loc_potheri_platform_view.jpg',
    area: 'Potheri / West',
    difficulty: 'medium',
    active: true,
  },
  {
    id: 'loc_potheri_station_entrance',
    name: 'Potheri Station West Entrance Arch',
    latitude: 12.825910,
    longitude: 80.039620,
    panoId: 'potheri_station_entrance',
    imageUrl: '/images/locations/loc_potheri_station_entrance.jpg',
    area: 'Potheri / West',
    difficulty: 'medium',
    active: true,
  },
  {
    id: 'loc_potheri_bridge_stairs',
    name: 'Potheri Footbridge Staircase Clue',
    latitude: 12.825550,
    longitude: 80.039780,
    panoId: 'potheri_bridge_stairs',
    imageUrl: '/images/locations/loc_potheri_bridge_stairs.jpg',
    area: 'Potheri / West',
    difficulty: 'hard',
    active: true,
  },
  {
    id: 'loc_potheri_tracks_overhead',
    name: 'Potheri High-Voltage Cantilever & Rails',
    latitude: 12.826010,
    longitude: 80.040250,
    panoId: 'potheri_tracks_overhead',
    imageUrl: '/images/locations/loc_potheri_tracks_overhead.jpg',
    area: 'Potheri / West',
    difficulty: 'hard',
    active: true,
  },
  {
    id: 'loc_potheri_gate_approach',
    name: 'Potheri Station Approach Roadway',
    latitude: 12.825780,
    longitude: 80.039520,
    panoId: 'potheri_gate_approach',
    imageUrl: '/images/locations/loc_potheri_gate_approach.jpg',
    area: 'Potheri / West',
    difficulty: 'medium',
    active: true,
  },

  // ZONE 4: CENTRAL CAMPUS (Java Green, Clock Tower & Central Avenue)
  {
    id: 'loc_java_green_clock_tower',
    name: 'Java Green & Clock Tower',
    latitude: 12.823120,
    longitude: 80.043810,
    panoId: 'clock_tower_java',
    imageUrl: '/images/locations/loc_java_green_clock_tower.jpg',
    area: 'Central Campus',
    difficulty: 'easy',
    active: true,
  },
  {
    id: 'loc_java_green_lawns',
    name: 'Java Green Seating Lawns Corner',
    latitude: 12.823250,
    longitude: 80.043920,
    panoId: 'java_green_lawns',
    imageUrl: '/images/locations/loc_java_green_lawns.jpg',
    area: 'Central Campus',
    difficulty: 'medium',
    active: true,
  },
  {
    id: 'loc_campus_walkway',
    name: 'SRM Central Avenue Walkway',
    latitude: 12.824120,
    longitude: 80.044120,
    panoId: 'campus_walkway_avenue',
    imageUrl: '/images/locations/loc_campus_walkway.jpg',
    area: 'Central Campus',
    difficulty: 'medium',
    active: true,
  },
  {
    id: 'loc_campus_walkway_close',
    name: 'Central Walkway Tree Canopy (Zoomed Detail)',
    latitude: 12.824120,
    longitude: 80.044120,
    panoId: 'campus_walkway_close',
    imageUrl: '/images/locations/loc_campus_walkway_close.jpg',
    area: 'Central Campus',
    difficulty: 'hard',
    active: true,
  },
  {
    id: 'loc_central_boulevard',
    name: 'SRM Main Campus Boulevard Corridor',
    latitude: 12.823950,
    longitude: 80.044350,
    panoId: 'central_boulevard',
    imageUrl: '/images/locations/loc_central_boulevard.jpg',
    area: 'Central Campus',
    difficulty: 'hard',
    active: true,
  },

  // ZONE 5: EAST CAMPUS / ACADEMIC BLOCKS (Bioengineering, Old Campus & Academic Block)
  {
    id: 'loc_academic_block_new',
    name: 'SRM Academic Block (2026 View)',
    latitude: 12.823612,
    longitude: 80.044521,
    panoId: 'academic_block_2026',
    imageUrl: '/images/locations/loc_academic_block_new.jpg',
    area: 'East Academic',
    difficulty: 'medium',
    active: true,
  },
  {
    id: 'loc_academic_windows_zoom',
    name: 'Academic Block Glass & Louver Matrix',
    latitude: 12.823720,
    longitude: 80.044610,
    panoId: 'academic_windows_zoom',
    imageUrl: '/images/locations/loc_academic_windows_zoom.jpg',
    area: 'East Academic',
    difficulty: 'hard',
    active: true,
  },
  {
    id: 'loc_old_campus',
    name: 'Old Engineering Campus Wing (August 2024)',
    latitude: 12.823850,
    longitude: 80.042810,
    panoId: 'old_campus_aug2024',
    imageUrl: '/images/locations/loc_old_campus.jpg',
    area: 'East Academic',
    difficulty: 'medium',
    active: true,
  },
  {
    id: 'loc_old_campus_arcade',
    name: 'Old Engineering Red Brick Arcade Corridor',
    latitude: 12.823920,
    longitude: 80.042950,
    panoId: 'old_campus_arcade',
    imageUrl: '/images/locations/loc_old_campus_arcade.jpg',
    area: 'East Academic',
    difficulty: 'hard',
    active: true,
  },
  {
    id: 'loc_bio_engineering_block',
    name: 'School of Bioengineering Entrance',
    latitude: 12.822530,
    longitude: 80.045120,
    panoId: 'bio_engineering_block',
    imageUrl: '/images/locations/loc_bio_engineering_block.jpg',
    area: 'East Academic',
    difficulty: 'medium',
    active: true,
  },
  {
    id: 'loc_bio_lab_entrance',
    name: 'Bioengineering Research Lab Portal',
    latitude: 12.822640,
    longitude: 80.045250,
    panoId: 'bio_lab_entrance',
    imageUrl: '/images/locations/loc_bio_lab_entrance.jpg',
    area: 'East Academic',
    difficulty: 'hard',
    active: true,
  },
];

async function main() {
  console.log('Seeding progressive difficulty locations with real photos...');
  // Clear non-current locations so only verified real photos are active
  await prisma.location.updateMany({ data: { active: false } });

  for (const loc of locations) {
    await prisma.location.upsert({
      where: { id: loc.id },
      update: loc,
      create: loc,
    });
  }
  const count = await prisma.location.count({ where: { active: true } });
  console.log(`Successfully seeded ${count} active locations across Easy, Medium, and Hard difficulty!`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
