import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const locations = [
  {
    id: 'loc_ub_front',
    name: 'University Building (UB) Main Entrance',
    latitude: 12.823612,
    longitude: 80.044521,
    panoId: 'CAoSLEFGMVFpcE1hV3B6TzQ0X3J4cTRvRUR3Wl90U1F1MjhjZ2V5TjJ1QzFEV1dJ',
    area: 'Main Campus',
    difficulty: 'easy',
    active: true,
  },
  {
    id: 'loc_tech_park',
    name: 'Tech Park (TP) IT & CSE Block',
    latitude: 12.824705,
    longitude: 80.045230,
    panoId: 'CAoSLEFGMVFpcE5yNVp3enU2dWlzM1h4SGcxNmY3VkhocW1pZVRfNmV5R01yZ0FF',
    area: 'Main Campus',
    difficulty: 'easy',
    active: true,
  },
  {
    id: 'loc_tp_ganesan_auditorium',
    name: 'Dr. T.P. Ganesan Auditorium',
    latitude: 12.821340,
    longitude: 80.038410,
    panoId: 'CAoSLEFGMVFpcE9hREp1TXk4Q1E0ektrTG1xYmV5X2w4Q0J4Y2xicFZZVUR0TVZF',
    area: 'South Campus',
    difficulty: 'easy',
    active: true,
  },
  {
    id: 'loc_main_arch_gate',
    name: 'Main Arch Gate (GST Road Entrance)',
    latitude: 12.823812,
    longitude: 80.041620,
    panoId: 'CAoSLEFGMVFpcE1KRHZqQWJpblhZTk5jYkJlQkxvd3lFTFcxY0p1ekNuQ3hGOW80',
    area: 'Gates',
    difficulty: 'easy',
    active: true,
  },
  {
    id: 'loc_potheri_railway_bridge',
    name: 'Potheri Railway Station Footbridge',
    latitude: 12.825634,
    longitude: 80.039845,
    panoId: 'CAoSLEFGMVFpcE5FTmR3NkptYy1aTGtDOW0ycnhnTXFjRGF3VWxQZzFYWjBvaW9r',
    area: 'Potheri',
    difficulty: 'medium',
    active: true,
  },
  {
    id: 'loc_java_green_clock_tower',
    name: 'Java Green & Clock Tower',
    latitude: 12.823120,
    longitude: 80.043810,
    panoId: 'CAoSLEFGMVFpcE1hclBvWWlfRFoxTGh6WkRFT3B0aE51UW80UGR2dWd2N2k0TGxI',
    area: 'Main Campus',
    difficulty: 'easy',
    active: true,
  },
  {
    id: 'loc_medical_college_hospital',
    name: 'SRM Medical College Hospital & Research Centre',
    latitude: 12.821125,
    longitude: 80.048740,
    panoId: 'CAoSLEFGMVFpcE5tNm9Zc01kQU1xOG5Jd0Q2ekl1QWd2cDR6U2RjTFZ3aG11bU1q',
    area: 'Medical Campus',
    difficulty: 'medium',
    active: true,
  },
  {
    id: 'loc_srm_dental_college',
    name: 'SRM Dental College & Hospital',
    latitude: 12.820210,
    longitude: 80.047830,
    panoId: 'CAoSLEFGMVFpcE1UOHVvSXRVNmZ0cmh2cEw5TWRfN1R2UkxscG56enZtdEZoM3Rz',
    area: 'Medical Campus',
    difficulty: 'medium',
    active: true,
  },
  {
    id: 'loc_paari_kaveri_hostel',
    name: 'Paari & Kaveri Hostel Quadrangle',
    latitude: 12.825510,
    longitude: 80.046520,
    panoId: 'CAoSLEFGMVFpcE96V1ZudVhRSlU3bE4wUHRQblFqSW1wR1V3Z3lhckR5V012NktX',
    area: 'Hostel Zone',
    difficulty: 'medium',
    active: true,
  },
  {
    id: 'loc_oori_adhiyaman_hostel',
    name: 'Oori & Adhiyaman Hostels Avenue',
    latitude: 12.826540,
    longitude: 80.045810,
    panoId: 'CAoSLEFGMVFpcE5VclZkZXZ5aW92S0F3MGpFdWV3a1dEa2xEb1B1ZHRiWGZCSW9M',
    area: 'Hostel Zone',
    difficulty: 'medium',
    active: true,
  },
  {
    id: 'loc_srm_global_hospital_gate',
    name: 'SRM Global Hospital Gate / Med Gate',
    latitude: 12.819850,
    longitude: 80.049530,
    panoId: 'CAoSLEFGMVFpcE1vOHJkQ3l0c3VqUWtVamFvVmtubmduRjFnTzI5Y1hRTVFvc3Nj',
    area: 'Medical Campus',
    difficulty: 'hard',
    active: true,
  },
  {
    id: 'loc_mech_workshop_block',
    name: 'Mechanical Engineering Workshop Lane',
    latitude: 12.824120,
    longitude: 80.043210,
    panoId: 'CAoSLEFGMVFpcE9qT1hIcU9fVGd3ckx1Qk56dG5hRGtEbE5qWjRLWTR5Tml2WkpO',
    area: 'Main Campus',
    difficulty: 'medium',
    active: true,
  },
  {
    id: 'loc_electrical_sciences_block',
    name: 'Electrical Sciences Block (ESB)',
    latitude: 12.824350,
    longitude: 80.044020,
    panoId: 'CAoSLEFGMVFpcE1oTm80aVVRZ0tKRE5KclF2d1ptS3V0N3BScXhHcmFad0RpdW1Z',
    area: 'Main Campus',
    difficulty: 'medium',
    active: true,
  },
  {
    id: 'loc_srm_hotel_royal_green',
    name: 'SRM Hotel & Royal Green Lawn',
    latitude: 12.822830,
    longitude: 80.040210,
    panoId: 'CAoSLEFGMVFpcE51b2tqckpIT2hkSG10bWpXSGhYTGk3WlVfVnl3RHRuRkhjV2lv',
    area: 'South Campus',
    difficulty: 'medium',
    active: true,
  },
  {
    id: 'loc_central_library_atrium',
    name: 'SRM Central Library & UB Atrium',
    latitude: 12.823520,
    longitude: 80.044310,
    panoId: 'CAoSLEFGMVFpcE1sOGF0WHd0eW0yS1pqSGt0VG13WldGWWZwVWRjVGZqS2d2U0lo',
    area: 'Main Campus',
    difficulty: 'easy',
    active: true,
  },
  {
    id: 'loc_potheri_main_road_estancia',
    name: 'Potheri Main Road / Estancia Junction',
    latitude: 12.827010,
    longitude: 80.042530,
    panoId: 'CAoSLEFGMVFpcE9zWmVrZFlhQ1pQSE9yVldXWVRrXzFRRnlvTG15NXZhTW16VnFN',
    area: 'Potheri',
    difficulty: 'hard',
    active: true,
  },
  {
    id: 'loc_arts_science_college',
    name: 'SRM College of Science & Humanities',
    latitude: 12.822010,
    longitude: 80.046020,
    panoId: 'CAoSLEFGMVFpcE16dGh1Qldvc090V2dLVFBvNlFwT2N1U0NuWWFmVlptSE92TVlO',
    area: 'Main Campus',
    difficulty: 'medium',
    active: true,
  },
  {
    id: 'loc_tech_park_food_court',
    name: 'Tech Park Fast Food & Canteen Walkway',
    latitude: 12.825020,
    longitude: 80.044810,
    panoId: 'CAoSLEFGMVFpcE5hT0twbXZyblpYQmd2WGhTT2lYc2hQdW1OekF0Qkh5a2F6T3B2',
    area: 'Main Campus',
    difficulty: 'easy',
    active: true,
  },
  {
    id: 'loc_bio_engineering_block',
    name: 'School of Bioengineering Block',
    latitude: 12.822530,
    longitude: 80.045120,
    panoId: 'CAoSLEFGMVFpcE1rMGVfTFpVTzZkcnFPT29oUW5nU0FqV0FscV9vUktlcVl4N2s4',
    area: 'Main Campus',
    difficulty: 'medium',
    active: true,
  },
  {
    id: 'loc_srm_sports_complex_ground',
    name: 'SRM Cricket & Football Grounds',
    latitude: 12.826020,
    longitude: 80.048030,
    panoId: 'CAoSLEFGMVFpcE5lRjRScDJlYmp5bVl3UURuM2xWVkJ0ZzlaTmx4c093aTFWcWtz',
    area: 'Sports Zone',
    difficulty: 'medium',
    active: true,
  },
  {
    id: 'loc_architecture_said_block',
    name: 'SRM School of Architecture & Interior Design (SAID)',
    latitude: 12.823920,
    longitude: 80.046810,
    panoId: 'CAoSLEFGMVFpcE1QZkRjVVR1dXRjRDRpY1p4Q0V5TXBNNlV3UFNhRWVrbFdrd2Nj',
    area: 'Main Campus',
    difficulty: 'hard',
    active: true,
  },
  {
    id: 'loc_believers_church_gate_3',
    name: 'Gate 3 / Believers Church Road',
    latitude: 12.824510,
    longitude: 80.048520,
    panoId: 'CAoSLEFGMVFpcE9sQml2b1d0ZTRuR2t0b3p0UnN5U3g0eFZ2S3l1Y0Z1R2p0SGp4',
    area: 'Gates',
    difficulty: 'hard',
    active: true,
  },
  {
    id: 'loc_abode_valley_back_gate',
    name: 'Abode Valley Road & Back Gate Connection',
    latitude: 12.826830,
    longitude: 80.049810,
    panoId: 'CAoSLEFGMVFpcE1tQW9Yc09rT0NuR3h0RzBwSDFqVXZ1Ulp4WHl2QmRqQ3R3T3hv',
    area: 'Potheri',
    difficulty: 'hard',
    active: true,
  },
  {
    id: 'loc_valliammai_gate',
    name: 'SRM Valliammai Engineering College Gate',
    latitude: 12.827210,
    longitude: 80.041230,
    panoId: 'CAoSLEFGMVFpcE5rM290UURmUVRrU2lqT2h1cTFRb3J2aVlsUGt2TFlscG1wVURv',
    area: 'Gates',
    difficulty: 'medium',
    active: true,
  },
  {
    id: 'loc_law_management_block',
    name: 'SRM Law College & Management Studies',
    latitude: 12.821810,
    longitude: 80.043520,
    panoId: 'CAoSLEFGMVFpcE1hV3B6TzQ0X3J4cTRvRUR3Wl90U1F1MjhjZ2V5TjJ1QzFEV1dK',
    area: 'Main Campus',
    difficulty: 'medium',
    active: true,
  },
  {
    id: 'loc_lake_view_kattankulathur',
    name: 'Kattankulathur Lake Bund Road',
    latitude: 12.828510,
    longitude: 80.044020,
    panoId: 'CAoSLEFGMVFpcE9sV2xVclJ1TGhvRGl2cTJ4UmJPTG9wVnZ3R1ltSHd1ZFRqR3h0',
    area: 'Potheri',
    difficulty: 'hard',
    active: true,
  },
  {
    id: 'loc_sannasi_hostel',
    name: 'Sannasi Boys Hostel Complex',
    latitude: 12.825830,
    longitude: 80.047210,
    panoId: 'CAoSLEFGMVFpcE5tT1drckxvT3d1V0huR3R5UmJqWXZ2T3d3WG1xVHRrU3N3VG9q',
    area: 'Hostel Zone',
    difficulty: 'hard',
    active: true,
  },
  {
    id: 'loc_senbagam_girls_hostel',
    name: 'Senbagam Girls Hostel Gate',
    latitude: 12.824820,
    longitude: 80.047510,
    panoId: 'CAoSLEFGMVFpcE14VHdwY2x0R3R2T2h4UDF3T3V0WWZ2c1N3Tmx1Wmd3UHRrVnlv',
    area: 'Hostel Zone',
    difficulty: 'hard',
    active: true,
  }
];

async function main() {
  console.log('Seeding SRM KTR locations into Campus Geo database...');
  for (const loc of locations) {
    await prisma.location.upsert({
      where: { id: loc.id },
      update: loc,
      create: loc,
    });
  }
  const count = await prisma.location.count();
  console.log(`Successfully seeded ${count} locations for SRM KTR & Potheri!`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
